name: 'Prepare'
description: 'Install PHP and Composer dependencies'

runs:
  using: "composite"

  steps:

  - name: Install PHP
    uses: shivammathur/setup-php@v2
    with:
      php-version: ${{ matrix.php }}
      extensions: dom, mbstring, zip, fileinfo
      coverage: none

  - name: Get Composer Cache Directory
    id: composer-cache
    run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
    shell: bash

  - name: Cache dependencies
    uses: actions/cache@v3
    with:
      path: ${{ steps.composer-cache.outputs.dir }}
      key: dependencies-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-os-${{ matrix.os }}-version-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}
      restore-keys: dependencies-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-os-${{ matrix.os }}-version-${{ matrix.dependency-version }}-composer-

  - name: Install Composer dependencies
    run: |
      composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
      composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist
    shell: bash
