name: Run Pest

on:
  workflow_call:

jobs:
  tests:
    name: Tests P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        php: ['8.3', '8.4']
        laravel: [11.*, 12.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: 11.*
            testbench: 9.*
          - laravel: 12.*
            testbench: 10.*
      fail-fast: true
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare
      uses: ./.github/workflows/prepare
    # - name: Restore cache
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: tmp/phpunit.cache
    #     key: "phpunit-cache-${{ github.run_id }}"
    #     restore-keys: |
    #       phpunit-cache-
    - name: Run Pest Tests
      run: ./vendor/bin/pest -p --bail --coverage --min=100
    # - name: Save cache
    #   uses: actions/cache/save@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     path: tmp/phpunit.cache
    #     key: "phpunit-cache-${{ github.run_id }}"
